name: Deploy Project
on:
  push:
    branches:
      - master
jobs:
  build_and_test:
    name: Java Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/checkout@v2
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: "11"
          architecture: x64
      - name: Run Maven
        run: mvn --settings settings.xml deploy
        env:
          PACKAGES_DATASTRUCTURES_TOKEN: ${{secrets.PACKAGES_HTML_TOKEN}}
